name: WordPress CI
on:
  push:
    branches:
      - 'pull_request'
  pull_request:
    types: [synchronize]
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_2 }}
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: echo "🖥️ Building..."
      - name: Cloning repository
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

  CodeInspection:
    runs-on: ubuntu-20.04
    needs: Build
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '16.0.2'
          distribution: 'adopt'
          fetch-depth: 0
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: SonarQube Scan
        run: ./gradlew sonarqube -PenvId="QA01"

  RunSmokeTests:
    runs-on: ubuntu-20.04
    needs: CodeInspection
    steps:
      - name: cloning repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '16.0.2'
          distribution: 'adopt'
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Build API Testing framework
        run: ./gradlew clean executeFeatures -PenvId="QA01" -PcucumberOptions="@Smoke"

  RunAcceptanceTests:
    runs-on: ubuntu-20.04
    needs: RunSmokeTests
    steps:
      - name: cloning repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '16.0.2'
          distribution: 'adopt'
          fetch-depth: 0
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Run Tests
        run: ./gradlew clean executeFeatures -PenvId="QA01" -PcucumberOptions="@Acceptance"
      - name: Publish cucumber report
        uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "build/cucumber/cucumber.json"

#      - name: Deploy report to Github Pages
#        if: always()
#        uses: peaceiris/actions-gh-pages@v2
#        env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: "reports/cucumber-html-reports/overview-features.html"